<?php
ini_set("display_errors", "on");
header('Content-Type: application/json');
include 'DAO.php';
ini_set("display_errors", "on"); 

if(isset($_GET["tempo"]) && isset($_GET["graf"])){

	$tempo = $_GET["tempo"];
	$graf = $_GET["graf"];
	$agreg = $_GET["agreg"];


	$conn = conectar();

	$sql = '';
	if($graf == 'cons_group'){
		if($tempo == 'franja'){
			$sql = "SELECT GRUPO_ID AS LABEL,DF.FRANJA_ID AS SUBLABEL, ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID 
			GROUP BY GRUPO_ID, DF.FRANJA_ID
			ORDER BY GRUPO_ID, DF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT GRUPO_ID AS LABEL,DF.DIA_SEMANA AS SUBLABEL, ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID 
			GROUP BY GRUPO_ID, DF.DIA_SEMANA
			ORDER BY GRUPO_ID, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.GRUPO_ID AS LABEL , DM.NUMERO AS SUBLABEL, ".$agreg."(FCM.CONSUMO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY FCM.GRUPO_ID, DM.NUMERO
			ORDER BY FCM.GRUPO_ID, DM.NUMERO";
		}
	}else if($graf == 'price_group'){
		if($tempo == 'franja'){
			$sql = "SELECT GRUPO_ID AS LABEL,DF.FRANJA_ID AS SUBLABEL, ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID 
			GROUP BY GRUPO_ID, DF.FRANJA_ID
			ORDER BY GRUPO_ID, DF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT GRUPO_ID AS LABEL,DF.DIA_SEMANA AS SUBLABEL, ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID 
			GROUP BY GRUPO_ID, DF.DIA_SEMANA
			ORDER BY GRUPO_ID, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.GRUPO_ID AS LABEL , DM.NUMERO AS SUBLABEL, ".$agreg."(FCM.PRECIO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY FCM.GRUPO_ID, DM.NUMERO
			ORDER BY FCM.GRUPO_ID, DM.NUMERO";
		}
	}else if($graf == 'cons_cat'){
		if($tempo == 'franja'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DF.FRANJA_ID AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID = FCF.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			GROUP BY DC.CATEGORIA_ID, DF.FRANJA_ID
			ORDER BY DC.CATEGORIA_ID, DF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID = FCD.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			GROUP BY DC.CATEGORIA_ID, DF.DIA_SEMANA
			ORDER BY DC.CATEGORIA_ID, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DM.NUMERO AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID =  FCM.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DC.CATEGORIA_ID, DM.NUMERO
			ORDER BY DC.CATEGORIA_ID, DM.NUMERO";
		}
	}else if($graf == 'price_cat'){
		if($tempo == 'franja'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DF.FRANJA_ID AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID = FCF.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			GROUP BY DC.CATEGORIA_ID, DF.FRANJA_ID
			ORDER BY DC.CATEGORIA_ID, DF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID = FCD.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			GROUP BY DC.CATEGORIA_ID, DF.DIA_SEMANA
			ORDER BY DC.CATEGORIA_ID, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DM.NUMERO AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_GROUP DG ON DG.GRUPO_ID =  FCM.GRUPO_ID 
			LEFT JOIN DM_CATEGORY DC ON DC.CATEGORIA_ID =  DG.CATEGORIA_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DC.CATEGORIA_ID, DM.NUMERO
			ORDER BY DC.CATEGORIA_ID, DM.NUMERO";
		}
	}else if($graf == 'cons_tipo_tarifa'){
		if($tempo == 'franja'){
			$sql = "SELECT FCF.TIPOTARIFA  AS LABEL, FCF.FRANJA_ID AS SUBLABEL, ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			GROUP BY FCF.TIPOTARIFA, FCF.FRANJA_ID
			ORDER BY FCF.TIPOTARIFA, FCF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.DIA_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.MES AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			GROUP BY FCM.TIPOTARIFA, FCM.MES
			ORDER BY FCM.TIPOTARIFA, FCM.MES";
		}
	}else if($graf == 'price_tipo_tarifa'){
		if($tempo == 'franja'){
			$sql = "SELECT FCF.TIPOTARIFA  AS LABEL, FCF.FRANJA_ID AS SUBLABEL, ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			GROUP BY FCF.TIPOTARIFA, FCF.FRANJA_ID
			ORDER BY FCF.TIPOTARIFA, FCF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.DIA_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.MES AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			GROUP BY FCM.TIPOTARIFA, FCM.MES
			ORDER BY FCM.TIPOTARIFA, FCM.MES";
		}
	}else if($graf == 'cons_tar_din'){
		if($tempo == 'franja'){
			$sql = "";
		}else if($tempo == 'dia'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.DIA_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.MES AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			GROUP BY FCM.TIPOTARIFA, FCM.MES
			ORDER BY FCM.TIPOTARIFA, FCM.MES";
		}
	}else if($graf == 'price_tar_din'){
		if($tempo == 'franja'){
			$sql = "";
		}else if($tempo == 'dia'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.DIA_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.MES AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			GROUP BY FCM.TIPOTARIFA, FCM.MES
			ORDER BY FCM.TIPOTARIFA, FCM.MES";
		}
	}else if($graf == 'cons_tarifa_holydays'){
		$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY FCD.TIPOTARIFA, DF.FESTIVO
		ORDER BY FCD.TIPOTARIFA, DF.FESTIVO";
	}else if($graf == 'price_tarifa_holydays'){
		$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY FCD.TIPOTARIFA, DF.FESTIVO
		ORDER BY FCD.TIPOTARIFA, DF.FESTIVO";
	}else if($graf == 'cons_holydays'){
		$sql = "SELECT 'Tipos de días' AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY DF.FESTIVO
		ORDER BY DF.FESTIVO";
	}else if($graf == 'price_holydays'){
		$sql = "SELECT 'Tipos de días' AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY DF.FESTIVO
		ORDER BY DF.FESTIVO";
	}else if($graf == 'cons_trimester'){
		$sql = "SELECT 'Trimestres' AS LABEL , DM.TRIMESTRE AS SUBLABEL, ".$agreg."(CONSUMO) AS VALUE
		FROM FT_CONSUMO_MENSUAL FCM
		LEFT JOIN DM_MES DM ON FCM.MES_ID = DM.MES_ID
		GROUP BY DM.TRIMESTRE
		ORDER BY DM.TRIMESTRE";
	}else if($graf == 'price_trimester'){
		$sql = "SELECT 'Trimestres' AS LABEL , DM.TRIMESTRE AS SUBLABEL, ".$agreg."(PRECIO) AS VALUE
		FROM FT_CONSUMO_MENSUAL FCM
		LEFT JOIN DM_MES DM ON FCM.MES_ID = DM.MES_ID
		GROUP BY DM.TRIMESTRE
		ORDER BY DM.TRIMESTRE";
	}else if($graf == 'cons_weekend'){
		$sql = "SELECT 'Tipos de días' AS LABEL, DF.FIN_SEMANA AS SUBLABEL,  ".$agreg."(CONSUMO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY DF.FIN_SEMANA
		ORDER BY DF.FIN_SEMANA";
	}else if($graf == 'price_weekend'){
		$sql = "SELECT 'Tipos de días' AS LABEL, DF.FIN_SEMANA AS SUBLABEL,  ".$agreg."(PRECIO) AS VALUE
		FROM FT_CONSUMO_DIARIO FCD
		LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
		GROUP BY DF.FIN_SEMANA
		ORDER BY DF.FIN_SEMANA";
	}


	consulta($sql, $conn);
}

?>
