<?php
ini_set("display_errors", "on");
header('Content-Type: application/json');
include 'DAO.php';

if(isset($_GET["tempo"]) && isset($_GET["graf"]) && isset($_GET["value"])){

	$tempo = $_GET["tempo"];
	$graf = $_GET["graf"];
	$agreg = $_GET["agreg"];
	$value = $_GET["value"];
	$conn = conectar();

	$sql = '';
	if($graf == 'cons_group'){   
		if($tempo == 'franja'){
			$sql = "SELECT DG.ACRONIMO AS LABEL,DF.FRANJA_ID AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCF.GRUPO_ID
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID 
			GROUP BY DG.ACRONIMO, DF.FRANJA_ID
			ORDER BY DG.ACRONIMO, DF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT DG.ACRONIMO AS LABEL,DF.DIA_SEMANA AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCD.GRUPO_ID
			LEFT JOIN DM_DIA DF ON DF.DIA_ID = FCD.DIA_ID 
			GROUP BY DG.ACRONIMO, DF.DIA_SEMANA
			ORDER BY DG.ACRONIMO, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT DG.ACRONIMO AS LABEL , DM.mes_año AS SUBLABEL, ".$agreg."(FCM.".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCM.GRUPO_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DG.ACRONIMO, DM.mes_año
			ORDER BY DG.ACRONIMO, DM.mes_año";
		}else if($tempo == 'festivo'){
			$sql = "SELECT DG.ACRONIMO AS LABEL,DF.FESTIVO AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCD.GRUPO_ID
			LEFT JOIN DM_DIA DF ON DF.DIA_ID = FCD.DIA_ID 
			GROUP BY DG.ACRONIMO, DF.FESTIVO
			ORDER BY DG.ACRONIMO, DF.FESTIVO";
		}else if($tempo == 'finsemana'){
			$sql = "SELECT DG.ACRONIMO AS LABEL,DF.FIN_SEMANA AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCD.GRUPO_ID
			LEFT JOIN DM_DIA DF ON DF.DIA_ID = FCD.DIA_ID 
			GROUP BY DG.ACRONIMO, DF.FIN_SEMANA
			ORDER BY DG.ACRONIMO, DF.FIN_SEMANA";
		}else if($tempo == 'trimestre'){
			$sql = "SELECT DG.ACRONIMO AS LABEL , DM.TRIMESTRE AS SUBLABEL, ".$agreg."(FCM.".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_GRUPO DG ON DG.GRUPO_ID = FCM.GRUPO_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DG.ACRONIMO, DM.TRIMESTRE
			ORDER BY DG.ACRONIMO, DM.TRIMESTRE";
		}

	}else if($graf == 'cons_cat'){
		if($tempo == 'franja'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, FCF.FRANJA_ID AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_FRANJA DF ON DF.FRANJA_ID = FCF.FRANJA_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCF.CATEGORIA_ID
			GROUP BY FCF.CATEGORIA_ID, FCF.FRANJA_ID
			ORDER BY FCF.CATEGORIA_ID, FCF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DD.DIA_SEMANA AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_DIA DD ON DD.DIA_ID = FCD.DIA_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCD.CATEGORIA_ID
			GROUP BY FCD.CATEGORIA_ID, DD.DIA_SEMANA
			ORDER BY FCD.CATEGORIA_ID, DD.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DM.mes_año AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCM.CATEGORIA_ID
			GROUP BY FCM.CATEGORIA_ID, DM.mes_año
			ORDER BY FCM.CATEGORIA_ID, DM.mes_año";
		}else if($tempo == 'festivo'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DD.FESTIVO AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_DIA DD ON DD.DIA_ID = FCD.DIA_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCD.CATEGORIA_ID
			GROUP BY FCD.CATEGORIA_ID, DD.FESTIVO
			ORDER BY FCD.CATEGORIA_ID, DD.FESTIVO";
		}else if($tempo == 'finsemana'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DD.FIN_SEMANA AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_DIA DD ON DD.DIA_ID = FCD.DIA_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCD.CATEGORIA_ID
			GROUP BY FCD.CATEGORIA_ID, DD.FIN_SEMANA
			ORDER BY FCD.CATEGORIA_ID, DD.FIN_SEMANA";
		}else if($tempo == 'trimestre'){
			$sql = "SELECT MIN(DC.NOMBRE) AS LABEL, DM.TRIMESTRE AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			LEFT JOIN DM_CATEGORIA DC ON DC.CATEGORIA_ID =  FCM.CATEGORIA_ID
			GROUP BY FCM.CATEGORIA_ID, DM.TRIMESTRE
			ORDER BY FCM.CATEGORIA_ID, DM.TRIMESTRE";
		}
	}else if($graf == 'cons_tipo_tarifa'){
		if($tempo == 'franja'){
			$sql = "SELECT DC.TIPO_ENERGIA  AS LABEL, FCF.FRANJA_ID AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_FRANJAS FCF
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCF.CLIENTE_ID
			GROUP BY DC.TIPO_ENERGIA, FCF.FRANJA_ID
			ORDER BY DC.TIPO_ENERGIA, FCF.FRANJA_ID";
		}else if($tempo == 'dia'){
			$sql = "SELECT DC.TIPO_ENERGIA  AS LABEL, DD.DIA_SEMANA AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCD.CLIENTE_ID
			LEFT JOIN DM_DIA DD ON DD.DIA_ID = FCD.DIA_ID
			GROUP BY DC.TIPO_ENERGIA, DD.DIA_SEMANA
			ORDER BY DC.TIPO_ENERGIA, DD.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT DC.TIPO_ENERGIA  AS LABEL, DM.mes_año AS SUBLABEL, ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCM.CLIENTE_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DC.TIPO_ENERGIA, DM.mes_año
			ORDER BY DC.TIPO_ENERGIA, DM.mes_año";
		}else if($tempo == 'festivo'){
			$sql = "SELECT DC.TIPO_ENERGIA AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCD.CLIENTE_ID
			LEFT JOIN DM_DIA DF ON DF.DIA_ID = FCD.DIA_ID
			GROUP BY DC.TIPO_ENERGIA, DF.FESTIVO
			ORDER BY DC.TIPO_ENERGIA, DF.FESTIVO";
		}else if($tempo == 'finsemana'){
			$sql = "SELECT DC.TIPO_ENERGIA AS LABEL, DF.FIN_SEMANA AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCD.CLIENTE_ID
			LEFT JOIN DM_DIA DF ON DF.DIA_ID = FCD.DIA_ID
			GROUP BY DC.TIPO_ENERGIA, DF.FIN_SEMANA
			ORDER BY DC.TIPO_ENERGIA, DF.FIN_SEMANA";
		}else if($tempo == 'trimestre'){
			$sql = "SELECT DC.TIPO_ENERGIA AS LABEL, DM.TRIMESTRE AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_CLIENTE DC ON DC.CLIENTE_ID = FCM.CLIENTE_ID
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY DC.TIPO_ENERGIA, DM.TRIMESTRE
			ORDER BY DC.TIPO_ENERGIA, DM.TRIMESTRE";
		}
	}else if($graf == 'cons_tar_din'){
		if($tempo == 'franja'){
			$sql = "";
		}else if($tempo == 'dia'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.DIA_SEMANA AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.DIA_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.DIA_SEMANA";
		}else if($tempo == 'mes'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.MES AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			GROUP BY FCM.TIPOTARIFA, FCM.MES
			ORDER BY FCM.TIPOTARIFA, FCM.MES";
		}else if($tempo == 'festivo'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.FESTIVO AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.FESTIVO
			ORDER BY FCD.TIPOTARIFA, DF.FESTIVO";
		}else if($tempo == 'finsemana'){
			$sql = "SELECT FCD.TIPOTARIFA AS LABEL, DF.FIN_SEMANA AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_DIARIO FCD
			LEFT JOIN DM_FECHA DF ON DF.FECHA_ID = FCD.FECHA_ID
			GROUP BY FCD.TIPOTARIFA, DF.FIN_SEMANA
			ORDER BY FCD.TIPOTARIFA, DF.FIN_SEMANA";
		}else if($tempo == 'trimestre'){
			$sql = "SELECT FCM.TIPOTARIFA AS LABEL, FCM.TRIMESTRE AS SUBLABEL,  ".$agreg."(".$value.") AS VALUE
			FROM FT_CONSUMO_MENSUAL FCM
			LEFT JOIN DM_MES DM ON DM.MES_ID = FCM.MES_ID
			GROUP BY FCM.TIPOTARIFA, FCM.TRIMESTRE
			ORDER BY FCM.TIPOTARIFA, FCM.TRIMESTRE";
		}
	}else{
		$sql = "SELECT GRUPO_ID AS LABEL, VARIABLES AS SUBLABEL, VALOR AS VALUE
		FROM DM_DEMOGRAFIA
		WHERE ASUNTO = '".$graf."'
		ORDER BY GRUPO_ID, VARIABLES";
	}
	
	consulta($sql, $conn);
	desconectar($conn);
}

?>
